--ozone-platform=wayland
--enable-features=UseOzonePlatform,VaapiVideoDecoder,AcceleratedVideoDecodeLinuxGL,AcceleratedVideoEncoder,VaapiIgnoreDriverChecks,PreferAV1ForHardwareVideoDecoder
--disable-features=Vulkan,DefaultANGLEVulkan,VulkanFromANGLE
