-- Set map leader to space
vim.g.mapleader = " "

-- Global Keybindings (Available everywhere)
local map = vim.keymap.set
local opts = { noremap = true, silent = true }

-- Window navigation
map('n', '<leader>wh', '<C-w>h', opts)
map('n', '<leader>wj', '<C-w>j', opts)
map('n', '<leader>wk', '<C-w>k', opts)
map('n', '<leader>wl', '<C-w>l', opts)

-- Window management
map('n', '<leader>ws', '<C-w>s', opts) -- Split horizontally
map('n', '<leader>wv', '<C-w>v', opts) -- Split vertically
map('n', '<leader>wc', '<C-w>c', opts) -- Close window
map('n', '<leader>wo', '<C-w>o', opts) -- Close others

-- Add keybindings to the attached LSP
vim.api.nvim_create_autocmd("LspAttach", {
    callback = function(e)
        local opts = { buffer = e.buf }
        vim.keymap.set("n", "K", function() vim.lsp.buf.hover() end, opts)
        vim.keymap.set("n", "J", function() vim.diagnostic.open_float() end, opts)
        vim.keymap.set("n", "[d", function() vim.diagnostic.goto_next() end, opts)
        vim.keymap.set("n", "]d", function() vim.diagnostic.goto_prev() end, opts)
        vim.keymap.set("n", "<leader>vws", function() vim.lsp.buf.workspace_symbol() end, opts)
        vim.keymap.set("n", "<leader>vca", function() vim.lsp.buf.code_action() end, opts)
        vim.keymap.set("n", "<leader>vrr", function() vim.lsp.buf.references() end, opts)
        vim.keymap.set("n", "<leader>vrn", function() vim.lsp.buf.rename() end, opts)
        vim.keymap.set("i", "<C-h>", function() vim.lsp.buf.signature_help() end, opts)

        -- Generated by yours truly ChatGPT:
        vim.keymap.set("n", "gk", function()
          local bufname = vim.api.nvim_buf_get_name(0)
          local ext = bufname:match("^.+(%..+)$") or ""
          ext = ext:lower()

          if ext == ".h" or ext == ".hpp" or ext == ".hxx" then
            vim.lsp.buf.definition()
          else
            vim.lsp.buf.declaration()
          end
        end, { buffer = e.buf, desc = "Jump between declaration/definition" })
        vim.keymap.set("n", "<leader>o", "<C-o>", { buffer = e.buf, desc = "Jump back in jumplist" })
        vim.keymap.set("n", "<leader>i", "<C-i>", { buffer = e.buf, desc = "Jump forward in jumplist" })


    end
})

-- Highlight yanked text for visual hint
vim.api.nvim_create_autocmd('TextYankPost', {
    pattern = '*',
    callback = function()
        vim.highlight.on_yank({
            higroup = 'IncSearch',
            timeout = 40,
        })
    end,
})

